### ISSUE TITLE
how to define css rules ? 

### ISSUE THREAD

**Issue by cappittall** [mlisook/paper-input-place#16]
Thank you for the nice element in advance, How can I change colors etc.?

**Comment by mlisook** [comment]
To change colors etc., you use the mixins and variables of `paper-input-container` which you can find listed on the [paper-input-container api page](https://www.webcomponents.org/element/PolymerElements/paper-input/elements/paper-input-container), but apply them to `paper-input-place`.  There are individual options on that page for all the parts and pieces of the control.

For example, if I want to make the underline green and thicker green when focused, I can use code like this:

```HTML
<template>
    <style>
      paper-input-place {
        width: 450px;
      }
      paper-input-place.make-it-green {        
          --paper-input-container-underline: {
            border-bottom: 2px solid green;
          }
          --paper-input-container-underline-focus: {
            border-bottom: 4px solid green;
          }
        }
    </style>
    <paper-input-place class="make-it-green" value="{{val}}" place="{{place}}" invalid="{{inv}}" api-key="[[apiKey]]" label="Pick a place, any place" hide-error></paper-input-place>
</template>
```

I hope this helps.  I'm happy to offer additional help if you need it.

**Comment by mlisook** [comment]
By the way, thanks for this question.  I really should have included some examples of styling on the project demo page.

**Comment by cappittall** [comment]
@mlisook Thank you very much ! (Before I tried to add container into my element) now It is clear.

**Comment by mlisook** [comment]
Closing this issue now that an example has been added to the README.md
