### ISSUE TITLE
How to change css of suggested list provided by search query?

### ISSUE THREAD

**Issue by gauravonly** [mlisook/paper-input-place#25]
I want to change the style of listing of the search query. How can it be done?

**Comment by mlisook** [comment]
Thank you for this question.  I should include some additional documentation and/or examples in the readme and demo for this element.

The list shown in the search query is from google maps places autocomplete.  In `paper-input-place` it can be styled with CSS, _but the CSS must be placed at the document level_, even if `paper-input-place` is inside another custom element. 

Example:  Add the following styles to the main document (e.g. index.html - _the styles must be in the document, not inside a custom element_):
```html
<style>
    .pac-container {
      background-color: lightblue;
      border: 2px darkolivegreen ;
      min-width: 450px;
    }
    .pac-item-query {
      font-size: 25px;
    }
    .pac-item:hover {
      background-color: lightgoldenrodyellow;
    }
    </style>
```
The result is (yes, I know it's really bad styling):
![pip-style-i25](https://user-images.githubusercontent.com/1044471/30512347-9711dbb6-9aaa-11e7-8185-95fcc489ed67.png)

There is documentation of the classes available on the [Google Developers Places Autocomplete page](https://google-developers.appspot.com/maps/documentation/javascript/places-autocomplete#style_autocomplete).

Again, thank you for this inquiry.

**Comment by gauravonly** [comment]
@mlisook thanks a lot for your reply. just wanted to inquire about one more doubt and i.e. what do you mean by adding css in document level (as index.html) but not custom component level? Can you explain a bit about this?

**Comment by mlisook** [comment]
The `paper-input-place` element can be anywhere you want.  Only the style needs to be in the document.

The reason for this is that the google places autocomplete adds HTML markup to the document body tag. Therefore the markup that shows the list is not inside `paper-input-place` but instead outside all custom elements.  So, the style classes have to be at the same level.

By way of example, in the demo for this element, `paper-input-place` is inside another custom element, `demo-pip`.  If I place the styles in `demo-pip` it will not work.

**Comment by gauravonly** [comment]
@mlisook  Great. Your component did work pretty well for me. I am so much thankful for your time and rapid responses as well. Kudos and keep making components like these.

**Comment by mlisook** [comment]
Thank you.  I'll close this issue and plan to improve documentation and samples to include styling the list.
