### ISSUE TITLE
how to auto focus input box in paper-input-place?

### ISSUE THREAD

**Issue by gauravonly** [mlisook/paper-input-place#26]
@mlisook - i need to autofocus the input box inside my application. Is there any way to do inside this component?

**Comment by mlisook** [comment]
Thank you for this question.

It is certainly not obvious how to do this, yet it can be done.  Here is are snippets you may be able to use in your application:

Inside another Polymer 1.x custom element:
```
this.$$('paper-input-place').$$('#locationsearch').$.nativeInput.focus();
```
Inside a Polymer 2.x custom element:
```
this.querySelector('paper-input-place').$$('#locationsearch').$.nativeInput.focus();
```
If `paper-input-place` is in the main HTML document:
```
document.querySelector('paper-input-place').$$('#locationsearch').$.nativeInput.focus();
```
I hopes this helps you. If not please continue the discussion here.

**Comment by gauravonly** [comment]
@mlisook Yeah great. It worked perfectly. Thanks once again and now this issue can be closed.

**Comment by gauravonly** [comment]
@mlisook Yeah great. It worked perfectly. Thanks once again and now this issue can be closed.
