### ISSUE TITLE
changing height of paper-input-place?

### ISSUE THREAD

**Issue by gauravonly** [mlisook/paper-input-place#27]
Is there a way to change the height of paper-input-place ? It changes the width but doesnot changes the height? Also what if i want to hide cross icon when there isn't any text in input box?

**Comment by mlisook** [comment]
You can style the different parts of the control with mixins as described in the style section of the readme (towards the bottom). You'll probably want to use `--paper-input-container` and `--paper-input-container-input` to change the height.

For hiding the icon you can add or remove a style that has the `--paper-input-place-prefix-icon-mixin` mixin defined to hide or show the icon.

**Comment by gauravonly** [comment]
Actually the problem was with the label which i was not using and it was taking up space inside paper-input-place. Though i got is working via accessing dom and hiding the label container inside it. when i was putting background into my paper-input it was looking odd without labels. Thanks once again @mlisook.
