### ISSUE TITLE
Bounding my search to a particular region?

### ISSUE THREAD

**Issue by gauravonly** [mlisook/paper-input-place#28]
Hey @mlisook . I want to localise my search i.e i want to show results for one country only (India in my case). There are not any properties that i can pass to the component till now i guess? How should i proceed to attain the desired result? Currently it by default takes US i guess.

**Comment by mlisook** [comment]
Thank you for this question.

Somehow, I was under the impression that the Google places autocomplete automatically biased its results to the user's current location. Yet in a quick web search, I can find no such function built in, so clearly I was wrong.

I think the best solution is to add additional properties to `paper-input-place` which allow optionally setting `country`, `bounds` (lat/lng bounding rectangle), and `types`.  This should be relatively straightforward to implement - I expect to publish a version update within 24 hours.

I will report back here on my progress.

**Comment by gauravonly** [comment]
Ohk thanks. Waiting for the update.

**Comment by mlisook** [comment]
The update has been merged.  You can update to version 1.9.5 of `paper-input-place' to get the new capability.

Example - limit results to India - use ISO code `IN` (not case sensitive):
```html
<paper-input-place label="Pick a place" api-key="your google api key" 
   value="{{tourstop.place}}" search-country-code="in">
</paper-input-place>
```
Example - search for establishments near Hyderabad:
```html
<paper-input-place label="Pick a place" api-key="your google api key" 
   value="{{tourstop.place}}" search-bounds="{north: 17.667, west: 78.084, south: 17.12, east: 78.742 }"
   search-type="establishment">
</paper-input-place>
```

I've also added a `focus()` method to the element, based on the earlier issue.

I hope this works out for you.

**Comment by gauravonly** [comment]
Hey @mlisook,
Thanks a lot for your time and this update. It is working supremely fine for me.
