### ISSUE TITLE
InvalidValueError: not an instance of HTMLInputElement

### ISSUE THREAD

**Issue by gauravonly** [mlisook/paper-input-place#34]
I am getting this issue from last few days and after a bit of debugging it is taking me to this error point in the component . Please have a look: 
_mapsApiLoaded | @ | paper-input-place.html:347
![screen shot 2018-01-24 at 2 47 53 am](https://user-images.githubusercontent.com/8857332/35301242-08db2fce-00b1-11e8-8dba-da8d557b4da3.png)

**Comment by mlisook** [comment]
Thank you for reporting this issue.

I believe this issue has to do with a recent change to `paper-input` [#609 2.x: Generate unique IDs for the input in the shadow root](https://github.com/PolymerElements/paper-input/pull/609).  I need to examine the best way to access the native input element in the updated `paper-input`.

**Comment by gauravonly** [comment]
@mlisook  - I have got the issue.  As you can see in the image in the highlighted yellow line  - this line need to be updated to this one ---           
this._places = new google.maps.places.Autocomplete(this.$.locationsearch.$.nativeInput, {}); 

I have checked  and this is working for me. So please check and make the changes in the newest version to the earliest.

**Comment by mlisook** [comment]
Fantastic!  Thank you!

**Comment by gauravonly** [comment]
@mlisook - when will you release the new version?

**Comment by mlisook** [comment]
Within the next 10 minutes.

**Comment by gauravonly** [comment]
thanks a ton :)

**Comment by mlisook** [comment]
The update has been merged in.  New release is 1.9.8.

Thanks for your help!
