### ISSUE TITLE
Paper input is not a HTMLElement

### ISSUE THREAD

**Issue by jobizzness** [mlisook/paper-input-place#36]
For some reason this component is not working and shows in the console that it needs a html element.

`_onApiLoad: function() {
            var rawInput;

            if (this.$.inputPaper.querySelector('input')) {
                rawInput = this.$.inputPaper.querySelector('input');
            } else {
                rawInput = this.$.inputPaper.root.querySelector('input');
            }

            this.autocomplete = new google.maps.places.Autocomplete(rawInput, this.options);
            google.maps.event.addListener(this.autocomplete, 'place_changed', this._onChangePlace.bind(this));
        },`

Changing the query selector to select the input element works.

PS: Sorry my explanation is terrible.

**Comment by mlisook** [comment]
Thank you for this report, but I'm not seeing the pasted code in the current or recent versions of the element.  Can you confirm what version of `paper-input-place` you have loaded (the element's `bower.json` file will have this information).

In the current version, the api attachment to the input element looks like this:
```JJS
_mapsApiLoaded: function () {
        if (!this._geocoder && !this._places && this.$.locationsearch && this.$.locationsearch.$.nativeInput) {
          this._geocoder = new google.maps.Geocoder();
          this._places = new google.maps.places.Autocomplete(this.$.locationsearch.$.nativeInput, {});
          google.maps.event.addListener(this._places, 'place_changed', this._onChangePlace.bind(this));
          this._setApiLoaded(true);
          this._searchBiasChanged();
          this.fire('api-loaded', {
            text: 'Google api is ready'
          });
        }
      },
```

**Comment by jobizzness** [comment]
Hi @mlisook i am so sorry wrong thread.
