### ISSUE TITLE
attrribute to set language for results

### ISSUE THREAD

**Issue by elf-pavlik** [mlisook/paper-input-place#40]
Hola :wave: 

We would like to adopt this compenent instead of the one we build for our app. For that we need to set language for the results.

https://developers.google.com/places/web-service/autocomplete#place_autocomplete_requests
> **language —** The language code, indicating in which language the results should be returned, if possible. Searches are also biased to the selected language; results in the selected language may be given a higher ranking. See the list of supported languages and their codes. Note that we often update supported languages so this list may not be exhaustive. If language is not supplied, the Place Autocomplete service will attempt to use the native language of the domain from which the request is sent.

We use it in our code https://github.com/vientos/vientos-app/blob/95e097130d75d854d7e76c2320b786a7ef7e0cf6/app/widgets/place-picker/place-picker.html#L12

I hope we can contribute PR with that feature, but if don't get chance to do it in next week maybe you and someone else would have capacity to implement it.

Gracias :exclamation:

**Comment by mlisook** [comment]
Thank you for submitting this.

I certainly would entertain a PR if you've developed one, or I could add the feature myself.  

There is a caveat, however.  What I'm seeing in the docs is that the language would have to be set in the library load (e.g. in `paper-input-place` `_computeUrl()` by adding a language parameter such as `&language=es`).  This is fine so long as either the `paper-input-place` is the only element using google maps api or any other element using the api (e.g. `google-map`) specifies the same language.  If not whichever element loads second will encounter an error with "api loaded twice".

Also note that the language is not settable after loading the api as are other parameters like countryCode, searchBounds, etc., currently handled by `_searchBiasChanged()`.  This means that the language must be set at the time the `paper-input-place` is loaded.

**Comment by elf-pavlik** [comment]
>  This is fine so long as either the `paper-input-place` is the only element using google maps api or any other element using the api (e.g. `google-map`) specifies the same language.

In our case only `paper-input-place` will use google maps api. I also think that if someone uses more elements they all would very likely specify the same language.

> I certainly would entertain a PR if you've developed one, or I could add the feature myself.

Possibly next week we could try to implement it, we would notify you here that we started working on it. If you have time and enthusiasm to implement it sooner, we would greatly appreciate to have possibility of having this functionality all ready and could simply focus on taking advantage of this component in our app.

**Comment by mlisook** [comment]
Thanks.  I might have time in the few days to do it, if so I will post here to let you know.

**Comment by elf-pavlik** [comment]
We also only use `libraries="places"` do you think it would make sense to also expose that option via attribute as well and then use it in `_computeUrl()` ?

**Comment by mlisook** [comment]
Yes, I think it is a good idea to have an option to load the minimal API.

**Comment by mlisook** [comment]
This change, for language preference and minimal API, is on my plan for today.  I expect to release an updated version by 21:00 (UTC -0600).

**Comment by mlisook** [comment]
Version 1.9.11 now includes these features.  The README has been updated to include the new attributes and a link to the supported language codes.

**Comment by elf-pavlik** [comment]
Works like a charm! Thank you for adding these features and apologies for very late reply and closing of this issue.
We hope soon to make a PR for exposing bounds / viewport from place details response.
