### ISSUE TITLE
upgrade to support Polymer 3.0

### ISSUE THREAD

**Issue by vhchung** [mlisook/paper-input-place#42]
Hi,
I used to use your component in my previous project. I have just upgraded my project to polymer 3.0 and I cannot use your component anymore. Please upgrade it to support Polymer 3.0

Thanks in advance.

**Comment by mlisook** [comment]
Hi,

This component is next on my list (I just upgraded `paper-map-info`).  I also need this updated for a current project.

I expect to publish the update in the next 1-2 days.

**Comment by vhchung** [comment]
Great. I'm so glad to hear that.

**Comment by mlisook** [comment]
This is up on [npm](https://www.npmjs.com/package/paper-input-place) now ...

**Comment by AlphaWong** [comment]
Thx man. It is very useful for my new polymer 3.0 project
:smile:

**Comment by vhchung** [comment]
Thanks man :+1:

**Comment by mlisook** [comment]
You are very welcome.

I'll be ready and happy to assist if any issues should arise.  

Closing the ticket now.
