### ISSUE TITLE
Can´t find any place

### ISSUE THREAD

**Issue by DominicWrege** [mlisook/paper-input-place#6]
Im a getting always this error message:

>  Invalid - please select a place

![screen shot 2016-08-20 at 15 13 11](https://cloud.githubusercontent.com/assets/7389000/17831689/152e33cc-66f0-11e6-8f03-cfb546f0e003.png)

**My Code:** 

`<paper-input-place api-key="[[myApiKey]]"   label="Pick a place, any place"></paper-input-place>`

Maybe I am using a wrong  Google api? I am using the **Google Maps JavaScript API**

**Comment by mlisook** [comment]
The control uses the Google Maps JavaScript API which should be enabled in your Google API Console.

If  you're saying you don't want to see the error highlighting in the control before a place has been selected, add the `hide-error attribute` to your markup (version 1.0.3, do a `bower update paper-input-place` if necessary, added in [Pull Request #3](https://github.com/mlisook/paper-input-place/pull/3) ).  

If, on the other hand you are saying that there is no autocomplete pick list shown, that would be a missing or bad API key.

Let me know if this solves the issue.

**Comment by DominicWrege** [comment]
I don´t know why but now it works. Why the label is colored red while I´m typing?
But with the `hide-error attribute` it´s fixed.

![18jmt](https://cloud.githubusercontent.com/assets/7389000/17831972/5503734c-66f8-11e6-9e45-62e569df4c63.gif)
