### ISSUE TITLE
paper-input-place.html:176 Uncaught TypeError: Cannot read property 'inputElement' of null

### ISSUE THREAD

**Issue by JaySunSyn** [mlisook/paper-input-place#8]
Thanks for this element!

I'm getting this error occasionally:
`paper-input-place.html:176 Uncaught TypeError: Cannot read property 'inputElement' of null`

The error is not thrown on ready(), but sometimes if I navigate a bit around my site.

Making async calls inside `_mapsApiLoaded` doesn't ever throw this error.

```
       this.async(function() {
          this._geocoder = new google.maps.Geocoder();
          this._places = new google.maps.places.Autocomplete(this.$$('#locationsearch').inputElement, {});
          google.maps.event.addListener(this._places, 'place_changed', this._onChangePlace.bind(this));
        }.bind(this))
```

May you patch the code?

**Comment by mlisook** [comment]
Thank you for identifying this critical bug.  I believe this could occur quite frequently.

I plan to push an update to correct this issue on October 2.

**Comment by mlisook** [comment]
I merged a change today to address this issue.  It is tagged with version 1.1.0, so a regular bower update paper-input-place will get the updated code installed.

BTW, I'm using one of your elements, polymer-tinymce, in a project I'm working on right now. Thank you for that, and thanks again for finding this bug in p-i-p.

**Comment by JaySunSyn** [comment]
Thanks a lot buddy! Good to har that!
